version: '3'
services:
  nginx:
    image: "nginx:latest"
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5001:80"
    networks:
      - nginx_nw
    depends_on:
      - flask

  flask:
    build: ./flask
    container_name: "flask"
    volumes:
      - ./flask:/opt/services/flask/src
    networks:
      - nginx_nw
      - postg_nw
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    networks:
      - postg_nw
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  nginx_nw:
    driver: bridge
  postg_nw:
    driver: bridge
